FROM alpine



RUN apk add python3

#/ # mkdir test
#/ # cd test
#/test # python3 -m venv venv
#/test # . venv/bin/activate
#(venv) /test # pip install Flask

# alternate: RUN python3 -m pip install Flask #no venv
# #create test.py and run it 
#(venv) /test # export FLASK_APP=test.py
#(venv) /test # flask run